 // 根据文件系统生成导航和侧边的一级结构
 const fs = require('fs');
 const path = require('path');
 const sidebarsDir = fs.readdirSync(path.resolve(process.cwd(), "./docs"));
 const sidebars = {};
 const navbars = [];
 sidebarsDir.forEach(dirName => {
  sidebars[dirName] = [{type: 'autogenerated', dirName}];
  navbars.push({
    type: 'docSidebar',
    position: 'left',
    sidebarId: dirName,
    label: dirName,
  })
 });

 module.exports = {
  sidebars,
  navbars
 }